<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;

class StandardModelCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $name = 'make:standardModel';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new Model based on the standard used by the Apomuden Backend Team';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Model';

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        return __DIR__ . '/Stubs/model.standard.stub';
    }

    protected function replaceClass($stub, $name)
    {
        $name = str_replace('Model','', $name);
        return parent::replaceClass($stub, $name); // TODO: Change the autogenerated stub
    }

    /**
     * Get the default namespace for the class.
     *
     * @param string $rootNamespace
     *
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace . '\Models';
    }
}
