<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class StandardRequestCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:standardRequest {name} {--t|table=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new Request based on the standard used by the Apomuden Backend Team';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Request';

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        return __DIR__ . '/Stubs/request.standard.stub';
    }

    protected function replaceClass($stub, $name)
    {
        $name = str_replace('Request', '', $name);
        return parent::replaceClass($stub, $name); // TODO: Change the autogenerated stub
    }

    protected function getPath($name)
    {
        $name = Str::endsWith($name, 'Request') ? $name : $name . 'Request';
        return parent::getPath($name); // TODO: Change the autogenerated stub
    }

    protected function replaceNamespace(&$stub, $name)
    {
        $classNameUnderscore = Str::snake(Str::afterLast(Str::pluralStudly($name), '\\'));
        $tableName = $this->option('table') ?? $classNameUnderscore;

        $tableColumns = Schema::getColumnListing($tableName);
        $requestParams = "";
        foreach ($tableColumns as $tableColumn) {
            if ($tableColumn == 'created_at' || $tableColumn == 'updated_at' || $tableColumn == 'deleted_at') {
                continue;
            }
            $requestParams .= '\'' . $tableColumn . '\' => \'bail\',' . PHP_EOL;
        }
        $stub = str_replace('DummyContent', $requestParams, $stub);
        //dd($requestParams);
        return parent::replaceNamespace($stub, $name); // TODO: Change the autogenerated stub
    }

    /**
     * Get the default namespace for the class.
     *
     * @param string $rootNamespace
     *
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace . '\Http\Requests';
    }
}
