<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Support\Str;

class StandardControllerCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $name = 'make:standardController';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a standard controller used by the Backend Team';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Controller';

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        return __DIR__ . '/Stubs/controller.standard.stub';
    }

    protected function replaceClass($stub, $name)
    {
        $name = str_replace('Controller', '', $name);
        return parent::replaceClass($stub, $name); // TODO: Change the autogenerated stub
    }

    protected function getPath($name)
    {
        $name = Str::endsWith($name, 'Controller') ? $name : $name . 'Controller';
        return parent::getPath($name); // TODO: Change the autogenerated stub
    }

    protected function replaceNamespace(&$stub, $name)
    {
        $userDefinedNamespace = str_replace($this->getDefaultNamespace(), '', $this->getNamespace($name));
        $stub = str_replace('UserDefinedNameSpace', $userDefinedNamespace . '\\', $stub);
        return parent::replaceNamespace($stub, $name); // TODO: Change the autogenerated stub
    }

    /**
     * Get the default namespace for the class.
     *
     * @param string $rootNamespace
     *
     * @return string
     */
    protected function getDefaultNamespace($rootNamespace = 'App')
    {
        return $rootNamespace . '\Http\Controllers';
    }
}
