<?php

use App\Models\ProductGenericName;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductGenericNameTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        ProductGenericName::query()->truncate();
        $records = [
            "Acetazolamide Injection, 500 mg",
            "Acetazolamide Tablet, 250 mg",
            "Acetylcysteine Injection, 200 mg/mL",
            "Acetylsalicylic Acid Tablet, 300 mg",
            "Acetylsalicylic Acid Tablet, 75 mg (Dispersible)",
            "Activated Charcoal Powder, 50 g",
            "Acyclovir Cream, 5%",
            "Acyclovir Eye Ointment, 3% ",
            "Acyclovir Injection, 250 mg vial",
            "Acyclovir Suspension, 200 mg/5 mL",
            "Acyclovir Tablet, 200 mg ",
            "Adrenaline Injection, 1 mg/1mL (1:1000)",
            "Adrenaline Injection, 1:10,000",
            "Adriamycin Injection, 50 mg",
            "Albendazole Syrup, 100 mg/5 mL",
            "Albendazole Tablet, 200 mg",
            "Albendazole Tablet, 400 mg",
            "Allopurinol Tablet, 100 mg",
            "Allopurinol Tablet, 300 mg",
            "Amino Acid Solution Injection, 10%",
            "Amino Acid Solution Injection, 20%",
            "Aminophylline Injection, 250 mg/10 mL",
            "Amiodarone Tablet, 200 mg",
            "Amitriptyline Tablet, 10 mg",
            "Amitriptyline Tablet, 25 mg",
            "Amitriptyline Tablet, 50 mg",
            "Amlodipine Tablet, 10 mg",
            "Amlodipine Tablet, 5 mg",
            "Amodiaquine + Artesunate Granular Powder, 150 mg + 50 mg ",
            "Amodiaquine + Artesunate Granular Powder, 75 mg + 25 mg  ",
            "Amodiaquine + Artesunate Tablet, 67.5 mg + 25 mg (6 tabs) ",
            "Amodiaquine + Artesunate Tablet, 135 mg + 50 mg (12 tabs) ",
            "Amodiaquine + Artesunate Tablet, 67.5 mg + 25mg (3's)",
            "Amodiaquine + Artesunate Tablet, 135 mg + 50 mg (3's)",
            "Amodiaquine + Artesunate Tablet, 270 mg + 100 mg (3's)",
            "Amodiaquine + Artesunate Tablet, 270 mg + 100 mg (6's)",
            "Amoxicillin + Clavulanic Acid Injection, 1.2g",
            "Amoxicillin + Clavulanic Acid Injection, 500 mg + 100 mg",
            "Amoxicillin + Clavulanic Acid Suspension, 250 mg + 62 mg ",
            "Amoxicillin + Clavulanic Acid Suspension, 400 mg + 57 mg",
            "Amoxicillin + Clavulanic Acid Tablet, 500 mg + 125 mg",
            "Amoxicillin + Clavulanic Acid Tablet, 875 mg + 125 mg",
            "Amoxicillin Capsule, 250 mg",
            "Amoxicillin Capsule, 500 mg",
            "Amoxicillin Suspension, 125 mg/5 mL",
            "Ampicillin Injection, 500 mg",
            "Anastrozole Tablet, 1 mg",
            "Anti RH Immunoglobulin Injection, 1500IU /5ml",
            "Aqueous Cream BP",
            "Artemether + Lumefantrine Suspension, (Powder For Reconstitution) 20 mg + 120 mg  / 5 mL",
            "Artemether + Lumefantrine Tablet, 20 mg + 120 mg (24’s)",
            "Artemether + Lumefantrine Tablet, 20 mg + 120 mg (6's)",
            "Artemether + Lumefantrine Tablet, 20 mg + 120 mg (12's)",
            "Artemether + Lumefantrine Tablet, 20 mg + 120 mg (18's)",
            "Artermether + Lumefantrine Dispersible,(20 mg + 120 mg) Tablet",
            "Artesunate Injection, 30 mg",
            "Artesunate Injection, 60 mg",
            "Artesunate injection 120mg",
            "Artesunate Suppository, 50 mg",
            "Artesunate suppository 100mg",
            "Atenolol + Hydrochlorthiazide Tablet, 100 mg + 25mg",
            "Atenolol + Hydrochlorthiazide Tablet, 50 mg + 25mg",
            "Atenolol Injection, 500 microgram/10 mL",
            "Atenolol Tablet, 100 mg ",
            "Atenolol Tablet, 25 mg",
            "Atenolol Tablet, 50 mg",
            "Atorvastatin Tablet, 10 mg",
            "Atorvastatin Tablet, 20 mg",
            "Atropine Eye Drops, 1%",
            "Atropine Injection, 0.6 mg/mL",
            "Azithromycin Capsule, 250 mg",
            "Azithromycin Oral Suspension, 200 mg/5 mL/15mL",
            "Azithromycin Oral Suspension, 200 mg/5 mL/30mL",
            "Badoe's Solution Injection, 1000 mL",
            "Beclometasone dipropionate Inhaler, 100 microgram/metered dose (200 doses)",
            "Beclometasone dipropionate Inhaler, 200 microgram/metered dose (200 doses)",
            "Beclometasone dipropionate Inhaler, 50 microgram/metered dose (200 doses)",
            "Bendroflumethiazide Tablet, 2.5 mg",
            "Benzatropine Injection, 1 mg/mL",
            "Benzatropine Tablet, 2 mg",
            "Benzoic Acid + Salicylic Acid Ointment, 6% + 3%",
            "Benzoyl Peroxide Cream, 10%",
            "Benzoyl Peroxide Cream, 5%",
            "Benzyl Benzoate Lotion, 25% ",
            "Benzylpenicillin Injection, 1 MU",
            "Benzylpenicillin Injection, 5 MU",
            "Betamethasone Valerate cream, 0.1%",
            "Betaxolol HCL Eye Drops, 0.5%",
            "Bisacodyl Tablet, 5 mg",
            "Bisoprolol Tablet 5 mg",
            "Bisoprolol Tablet 10 mg",
            "Bromocriptine Tablet, 2.5 mg",
            "Budesonide + Formoterol Inhaler 160 microgram/4.5 microgram (60 Doses)",
            "Budesonide + Formoterol Inhaler 80 microgram/4.5 microgram (60 Doses)",
            "Budesonide DPI, 100 microgram (100 Doses)",
            "Budesonide DPI, 200 microgram (100 Doses)",
            "Calamine Cream, 15% ",
            "Calamine Lotion, 15% ",
            "Calciferol Tablet, 10,000 units",
            "Calcium  Gluconate Injection, 100 mg/mL in 10 mL",
            "Calcium Carbonate Tablet, 500 mg",
            "Calcium with Vitamin D Tablet, (97 mg + 10 microgram)",
            "Capecitabine Tablet, 500 mg",
            "Carbamazepine Sustained-Release Tablet, 200mg",
            "Carbamazepine Sustained-Release Tablet, 400mg",
            "Carbamazepine Tablet, 100 mg",
            "Carbamazepine Tablet, 200 mg",
            "Carbimazole Tablet, 20 mg",
            "Carbimazole Tablet, 5 mg ",
            "Carbocisteine Paediatric Syrup , 125 mg/5 mL ",
            "Carbocisteine Syrup, 250 mg/5 mL",
            "Carvedilol Tablet 3.125 mg",
            "Carvedilol Tablet 12.5 mg",
            "Cefaclor Capsule, 250 mg",
            "Cefaclor Capsule, 500 mg",
            "Cefaclor Suspension, 125 mg/5 mL",
            "Cefaclor Suspension, 250 mg/5 mL",
            "Cefotaxime Injection, 1 g ",
            "Cefotaxime Injection, 500 mg",
            "Ceftriazone Injection, 1g ",
            "Ceftriazone Injection, 500 mg ",
            "Cefuroxime Injection, 750 mg ",
            "Cefuroxime Injection 1.5 g",
            "Cefuroxime Suspension, 125 mg/5 mL",
            "Cefuroxime Tablet, 125 mg",
            "Cefuroxime Tablet, 250 mg ",
            "Celecoxib Tablet 100 mg",
            "Celecoxib Tablet 200 mg",
            "Cetirizine Syrup, 5 mg/5 mL",
            "Cetirizine Tablet, 10 mg",
            "Cetrimide Solution",
            "Chloramphenicol Ear Drops, 5%",
            "Chloramphenicol Eye Drops, 0.5%",
            "Chloramphenicol Eye Ointment, 1%",
            "Chloramphenicol Injection, 1 g",
            "Chloramphenicol Suspension, 125mg/5mL",
            "Chlorhexidine Cream, 1%",
            "Chlorhexidine Gel 7.1 % ( digluconate ) delivering 4% chlorhexidine",
            "Chlorhexidine Mouth wash 0.12%",
            "Chlorhexidine Solution, 2.5%",
            "Chlorphenamine Syrup, 2 mg/5 mL",
            "Chlorphenamine Tablet, 4 mg",
            "Chlorpromazine Injection, 25 mg/mL in 2 mL",
            "Chlorpromazine Tablet, 100 mg",
            "Chlorpromazine Tablet, 25 mg",
            "Chlorpromazine Tablet, 50 mg",
            "Cholera Replacement Fluid Injection, (5:4:1) 1 litre",
            "Cholera Replacement Fluid Injection, (5:4:1), 500ml",
            "Ciprofloxacin + Tinidazole Tablet, 500 mg + 500mg",
            "Ciprofloxacin Eye Drops, 0.3%",
            "Ciprofloxacin Infusion, 2 mg/mL in 100 mL",
            "Ciprofloxacin Tablet, 250 mg ",
            "Ciprofloxacin Tablet, 500 mg ",
            "Clarithromycin Capsule, 250 mg",
            "Clarithromycin Capsule, 500 mg ",
            "Clarithromycin Paediatric Suspension, 125 mg/5 mL",
            "Clindamycin Capsule, 150 mg",
            "Clindamycin Injection, 150 mg/mL in 2 mL",
            "Clindamycin Suspension, 75 mg/5 mL",
            "Clindamycin Topical Solution, 1%",
            "Clobetasol Propionate Cream, 0.05%",
            "Clotrimazole + Hydrocortisone Cream, 1% +1%",
            "Clotrimazole Cream, 1% ",
            "Clotrimazole Cream, 2% ",
            "Clotrimazole Pessary, 100 mg",
            "Clotrimazole Pessary, 200 mg",
            "Clotrimazole Pessary, 500 mg",
            "Cloxacillin Injection, 250 mg",
            "Cloxacillin Injection, 500 mg",
            "Codeine Tablet, 30 mg",
            "Conjugated Oestrogen + Norgesterol Tablet, 625 microgram + 150 microgram",
            "Conjugated Oestrogen Tablet, 625 microgram ",
            "Conjugated Oestrogen Vaginal cream, 625 microgram/g",
            "Corticosteroid + Antibiotic Eye Drops ",
            "Corticosteroid + Antibiotic Eye Ointment ",
            "Co-trimoxazole Suspension, (200+40) mg/5 mL",
            "Cotrimoxazole Tablet, (400+80) mg ",
            "Cyclopentolate Eye Drops, 1%",
            "Cyclophosphamide Injection, 500 mg",
            "Dalteparin Sodium Injection, 5000 units/0.2 mL ",
            "Darrow's Solution Injection, Half Strength 250 mL",
            "Dexamethasone Eye Drops, 1%",
            "Dexamethasone Eye Ointment, 1%",
            "Dexamethasone Injection, 4 mg/mL",
            "Dexamethasone Injection, 8 mg/2 mL",
            "Dexamethasone Tablet, 500 microgram",
            "Dextromethorphan Containing Cough Syrup",
            "Dextrose in Sodium Chloride Intravenous Infusion, 4.3% in 0.18% (250 mL)",
            "Dextrose in Sodium Chloride Intravenous Infusion, 5% in 0.9% (500 mL)",
            "Dextrose Infusion, 10% (250 mL) ",
            "Dextrose Infusion, 10% (500 mL)",
            "Dextrose Infusion, 5% (250 mL)",
            "Dextrose Infusion, 5% (500 mL)",
            "Dextrose Infusion, 50% (250 mL)",
            "Diazepam Injection, 5 mg/mL in 2 mL",
            "Diazepam Rectal Tubes, 2 mg/mL in 1.25 mL",
            "Diazepam Tablet, 10 mg ",
            "Diazepam Tablet, 5 mg",
            "Diclofenac Capsule, 75 mg",
            "Diclofenac Gel",
            "Diclofenac Injection, 75mg/3mL",
            "Diclofenac Suppository, 100 mg",
            "Diclofenac Suppository, 50 mg",
            "Diclofenac Tablet, 50 mg",
            "Diethylstilboestrol Tablet, 1 mg",
            "Diethylstilboestrol Tablet, 5 mg",
            "Digoxin Elixir, 50 microgram/mL",
            "Digoxin Tablet, 125 microgram",
            "Digoxin Tablet, 250 microgram",
            "Digoxin Tablet, 62.5 microgram",
            "Dihydroartemisin + Piperaquine Granular Powder, 10 mg + 80 mg ",
            "Dihydrocodeine Tablet, 30 mg",
            "Disopyramide Capsule, 100 mg",
            "Disopyramide Phosphate Injection, 10 mg/mL in 5 mL",
            "Docetaxel Injection, 20 mg/mL",
            "Domperidone Tablet, 10 mg",
            "Dopamine Injection, 40 mg/mL in 5 mL",
            "Doxapram Injection, 20 mg/mL in 5 mL",
            "Doxycycline Capsule, 100 mg",
            "Enoxaparin Sodium Injection, 40 mg/0.4 mL ",
            "Ephedrine HCI Injection, 30 mg/mL",
            "Ephedrine Nasal Drops, 0.5%",
            "Ephedrine Nasal Drops, 1%",
            "Ergometrine Injection, 0.2 mg/mL",
            "Ergometrine Injection, 0.5 mg/ml",
            "Ergometrine Tablet, 0.5 mg",
            "Ergotamine Tablet, 2 mg",
            "Erythromycin Syrup, 125 mg/5 mL",
            "Erythromycin Tablet, 250 mg",
            "Esomeprazole Capsule, 20 mg",
            "Esomeprazole Capsule, 40 mg",
            "Ethosuximide Syrup, 250 mg/5 mL",
            "Ethosuximide Tablet, 250 mg",
            "Ferric Ammonium Citrate Mixture (FAC)",
            "Ferrous Fumarate Tablet, 100 mg (Elemental Iron)",
            "Ferrous Sulphate (BPC) Syrup, 60 mg/5 mL",
            "Ferrous Sulphate + Folic Acid Tablet, 50 mg (Elemental Iron) + 400 microgram ",
            "Ferrous Sulphate Tablet, 60 mg (Elemental iron)",
            "Finasteride Tablet, 5 mg",
            "Flucloxacillin Capsule, 250 mg",
            "Flucloxacillin Injection, 250 mg",
            "Flucloxacillin Injection, 500 mg",
            "Flucloxacillin Suspension, 125 mg/5 mL",
            "Fluconazole Capsule, 150 mg",
            "Fluconazole Capsule, 200 mg",
            "Fluconazole Suspension, 10 mg/mL",
            "Fluconazole Suspension, 50 mg/5 mL",
            "Fluconazole Tablet, 50 mg",
            "Fludrocortisone Tablet, 100 microgram",
            "Fluoxetine Capsule, 20 mg",
            "Flupentixol Tablet, 1mg",
            "Flupentixol Tablet, 500 microgram",
            "Fluphenazine Deconoate Injection, 25 mg/mL",
            "Fluticasone + Salmeterol Inhaler, 250 microgram/50 microgram (60 Doses)",
            "Fluticasone MDI, 125 microgram (120 Dose)",
            "Fluticasone MDI, 250 microgram (120 Dose)",
            "Fluvastatin Capsule, 20 mg",
            "Folic Acid Tablet, 5 mg ",
            "Furosemide Injection, 10 mg/mL in 2 mL",
            "Furosemide Tablet, 40 mg",
            "Gelatin Infusion (Succinylated Gelatin)",
            "Gentamicin Ear Drops, 0.3%",
            "Gentamicin Eye Drops, 0.3%",
            "Gentamicin Injection, 40 mg/mL in 2 mL",
            "Glibenclamide Tablet, 5 mg",
            "Gliclazide Tablet, 80 mg",
            "Glimepiride Tablet, 1 mg",
            "Glimepiride Tablet, 2 mg",
            "Glimepiride Tablet, 3 mg",
            "Glimepiride Tablet, 4 mg",
            "Glucagon Injection, 1 mg",
            "Glyceryl Trinitrate Sublingual Tablet, 500 microgram",
            "Granisetron Injection, 1 mg/1mL",
            "Granisetron Tablet, 1 mg",
            "Griseofulvin Suspension, 125 mg/5 mL",
            "Griseofulvin Tablet, 125 mg",
            "Griseofulvin Tablet, 500 mg",
            "Guaifenesin Containing Expectorant Syrup",
            "Haloperidol Injection, 5 mg/5 mL ",
            "Haloperidol Tablet, 0.5 mg",
            "Haloperidol Tablet, 10 mg",
            "Haloperidol Tablet, 5 mg",
            "Heparin Injection, 1000 units/mL in 5 mL ",
            "Heparin Injection, 5000 units/mL in 1mL ",
            "Heparin Injection, 5000 units/mL in 5 mL ",
            "Human Immune Tetanus Globulins Injection, 250 IU/mL",
            "Human Immune Tetanus Globulins Injection, 1,500 IU/mL (ATS)",
            "Hydralazine Injection, 20 mg",
            "Hydralazine Tablet, 25 mg",
            "Hydrocortisone Cream, 1% ",
            "Hydrocortisone Eye Drops, 1%",
            "Hydrocortisone Eye Ointment, 1%",
            "Hydrocortisone Sodium Succinate Injection, 100mg",
            "Hydroxocobalamin Injection, 1 mg/mL",
            "Hyoscine Butylbromide Injection, 20 mg/ mL ",
            "Hyoscine Butylbromide Tablet, 10 mg ",
            "Ibuprofen Suspension, 100 mg/5 mL",
            "Ibuprofen Tablet, 200 mg",
            "Ibuprofen Tablet, 400 mg",
            "Imipramine Tablet, 25 mg",
            "Ipratropium  Bromide  Nebulizer  250 micrograms",
            "Ipratropium Bromide Nebulizer 500 micrograms ",
            "Insulin premixed (30/70) HM Injection, 100 units/mL in 10 mL",
            "Insulin Soluble HM, 100 units/mL in 10 mL",
            "Intralipid Solution (for TPN)",
            "Iron (III) Polymaltose Complex Capsule",
            "Iron (III) Polymaltose Complex Suspension",
            "Iron Dextran Injection, 100mg/2mL",
            "Iron Sucrose Injection, 20 mg/mL",
            "Isophane Insulin Injection (HM), 100 units/mL in 10 mL",
            "Isosorbide Dinitrate Tablet, 10 mg",
            "Itraconazole Capsule, 100 mg",
            "Itraconazole Suspension, 10 mg/mL",
            "Ketoconazole Cream, 30g",
            "Ketoconazole Tablet, 200 mg",
            "Labetalol Injection, 5 mg/mL in 20 mL",
            "Labetalol Tablet, 100 mg",
            "Labetalol Tablet, 200 mg",
            "Lactulose Liquid 3.1–3.7 g/5 mL",
            "Levothyroxine Sodium Tablet, 100 microgram",
            "Levothyroxine Sodium Tablet, 25 microgram",
            "Levothyroxine Sodium Tablet, 50 microgram",
            "Lidocaine Cream, 2%",
            "Lidocaine Gel, 4%",
            "Lisinopril + Hydrochlorthiazide Tablet, (10 mg + 12.5 mg)",
            "Lisinopril + Hydrochlorthiazide Tablet, (20 mg + 12.5 mg)",
            "Lisinopril Tablet, 10 mg",
            "Lisinopril Tablet, 2.5 mg",
            "Lisinopril Tablet, 20 mg",
            "Lisinopril Tablet, 5 mg",
            "Lodoxamide Eye Drops, 0.1%",
            "Lorazepam Injection, 4 mg/mL in 1mL",
            "Lorazepam Tablet, 1 mg",
            "Lorazepam Tablet, 2 mg",
            "Lorazepam Tablet, 2.5 mg",
            "Losartan Tablet, 100 mg",
            "Losartan Tablet, 25 mg",
            "Losartan Tablet, 50 mg",
            "Magnesium Sulphate Injection, 20% (10 mL)",
            "Magnesium Sulphate Injection, 50% (10 mL)",
            "Magnesium Sulphate Salt",
            "Magnesium Trisilicate + Aluminium Hydroxide Mixture ",
            "Magnesium Trisilicate + Aluminium",
            "Magnesium Trisilicate Mixture ",
            "Magnesium Trisilicate Tablet, 500 mg",
            "Mannitol Injection, 10% ",
            "Mannitol Injection, 20% ",
            "Mebendazole Suspension, 100 mg/5 mL",
            "Mebendazole Tablet, 100 mg",
            "Mebendazole Tablet, 500 mg",
            "Mebeverine Tablet, 135 mg",
            "Medroxyprogesterone Acetate Tablet, 5 mg",
            "Mefenamic Acid Capsule, 250 mg",
            "Mefenamic Acid Tablet, 500 mg",
            "Metformin Tablet, 500 mg",
            "Methotrexate Injection, 2.5 mg/ mL",
            "Methotrexate Injection, 25 mg/ mL in 2mL",
            "Methotrexate Tablet, 10 mg",
            "Methotrexate Tablet, 2.5 mg",
            "Methyl Cellulose Eye Drops, 0.3%",
            "Methyldopa Tablet, 250 mg",
            "Metoclopramide Injection, 5 mg/mL in 2 mL",
            "Metoclopramide Syrup, 5 mg/5 mL",
            "Metoclopramide Tablet, 10 mg",
            "Metolazone Tablet, 5 mg",
            "Metoprolol Tartrate Tablet 100 mg",
            "Metronidazole Injection, 5 mg/mL in 100 mL",
            "Metronidazole Suppository, 500 mg",
            "Metronidazole Suspension, 100 mg/5 mL (as benzoate)",
            "Metronidazole Suspension, 200 mg/5 mL(as benzoate)",
            "Metronidazole Tablet, 200 mg",
            "Metronidazole Tablet, 400 mg",
            "Miconazole + Hydrocortisone Cream, 2% + 1%",
            "Miconazole Cream, 2%",
            "Miconazole Oral Gel, 25 mg/mL",
            "Miconazole Ovule, 400 mg",
            "Midazolam Injection, 5 mg/5mL",
            "Midazolam Tablet, 15 mg",
            "Morphine Injection, 10 mg/mL",
            "Morphine Injection, 10 mg/mL (Preservative free)",
            "Morphine Sulphate Tablet, 10 mg (Slow release)",
            "Morphine Sulphate Tablet, 30 mg (Slow release)",
            "Multivitamin Drops",
            "Multivitamin Syrup ",
            "Multivitamin Tablet ",
            "Naloxone Injection, 400 microgram/mL in 1ml",
            "Neomycin Tablet, 500 mg",
            "Neostigmine Bromide Tablet, 15 mg",
            "Neostigmine Injection, 2.5 mg/mL",
            "Nifedipine Capsule, 10 mg ",
            "Nifedipine Tablet, 10 mg (slow release)",
            "Nifedipine Tablet, 20 mg (slow release)",
            "Nifedipine Tablet, 30 mg (GITS)",
            "Nitrofurantoin Tablet, 100 mg",
            "Norethisterone Tablet, 5 mg",
            "Nystatin Ointment, 100,000 IU",
            "Nystatin Pessary, 100,000 IU",
            "Nystatin Suspension, 100,000 IU/mL",
            "Nystatin Tablet, 500,000 IU",
            "Omeprazole Injection, 40 mg",
            "Omeprazole Tablet, 20 mg",
            "Oral Rehydration Salts Powder",
            "Oxytocin Injection, 10 units/mL",
            "Oxytocin Injection, 5 units/mL",
            "Paclitaxel Injection, 100 mg/16.7mL",
            "Paracetamol Suppository, 125 mg",
            "Paracetamol Suppository, 250 mg",
            "Paracetamol Suppository, 500 mg",
            "Paracetamol Syrup, 120 mg/5 mL",
            "Paracetamol Tablet, 500 mg",
            "Paraffin Liquid",
            "Pethidine Injection, 50 mg/mL in 2 mL",
            "Phenobarbital Elixir, 15 mg/5 mL",
            "Phenobarbital Injection, 200 mg/mL",
            "Phenobarbital Tablet, 30 mg",
            "Phenobarbital Tablet, 60 mg",
            "Phenol 5% in Almond Oil Injection",
            "Phenoxymethyl Penicillin Tablet, 250 mg",
            "Phenytoin Injection, 50 mg/mL  in 5 mL",
            "Phenytoin Sodium Capsule, 100 mg",
            "Phenytoin Sodium Tablet, 100 mg",
            "Phytomenadione Injection, 1 mg/mL (Paediatric)",
            "Phytomenadione Injection, 10 mg/mL",
            "Pilocarpine Eye Drops, 2%",
            "Pilocarpine Eye Drops, 4%",
            "Pioglitazone Tablet, 15 mg",
            "Pioglitazone Tablet, 30 mg",
            "Piracetam Tablet, 800 mg",
            "Potassium Chloride Injection, 20 mEq/10 mL",
            "Potassium Chloride Tablet, 600 mg (Enteric coated)",
            "Potassium Citrate Mixture BP",
            "Povidone Iodine Aqueous Solution, 10% ",
            "Povidone Iodine Ointment, 10%",
            "Praziquantel Tablet, 600 mg",
            "Prazosin Tablet, 500 microgram",
            "Prednisolone Eye Drops, 0.5%",
            "Prednisolone Eye Drops, 1%",
            "Prednisolone Tablet, 5 mg",
            "Prednisolone 5mg Dispersible Tablets",
            "Prednisolone Oral Solution, 5mg/5ml",
            "Primidone Tablet, 250 mg",
            "Procaine Benzylpenicillin Injection, 4 MU",
            "Promethazine Hydrochloride Elixir, 5 mg/5 mL",
            "Promethazine Hydrochloride Injection, 25 mg/mL in 2 mL",
            "Promethazine Hydrochloride Tablet, 25 mg",
            "Promethazine Theoclate Tablet, 25 mg ",
            "Propranolol Injection, 1 mg/mL in 1mL",
            "Propranolol Tablet, 10 mg",
            "Propranolol Tablet, 40 mg",
            "Propranolol Tablet, 80 mg",
            "Propylthiouracil Tablet, 50 mg",
            "Protamine Sulphate Injection, 10 mg/mL in 5 mL",
            "Quinine Injection, 300 mg/mL in 2 mL",
            "Quinine Syrup, 75 mg/5 mL",
            "Quinine Tablet, 300 mg",
            "Ramipril Tablet, 2.5 mg",
            "Ramipril Tablet, 5 mg",
            "Ranitidine Tablet, 150 mg",
            "Retinol Soft Capsule, 200,000 IU",
            "Ringer - Lactate Solution, 500 mL",
            "Risperidone Liquid, 1 mg/mL",
            "Risperidone Tablet, 1 mg",
            "Risperidone Tablet, 2 mg",
            "Risperidone Tablet, 500 microgram",
            "Salbutamol Inhaler, 100 microgram/metered dose, 200 doses",
            "Salbutamol Nebules, 2.5 mg ",
            "Salbutamol Nebules, 5 mg ",
            "Salbutamol Sulphate Injection, 500 microgram/mL in 1mL",
            "Salbutamol Syrup, 2 mg/5 mL",
            "Salicylic Acid Ointment, 2% ",
            "Secnidazole Tablet, 500 mg",
            "Selenium Sulphide Shampoo, 2.5%",
            "Sertraline Tablet, 100 mg",
            "Sertraline Tablet, 50 mg",
            "Silver Sulphadiazine Cream, 1% ",
            "Simple Linctus  BPC (Paediatric)",
            "Simple Linctus BPC",
            "Simvastatin Tablet, 10 mg",
            "Simvastatin Tablet, 20 mg",
            "Simvastatin Tablet, 40 mg",
            "Simvastatin Tablet, 80 mg",
            "Sodium Bicarbonate Injection, 8.4% in 10 mL",
            "Sodium Chloride Infusion, 0.45% (250 mL)",
            "Sodium Chloride Infusion, 0.9% (500 mL)",
            "Sodium Chloride Nasal Drops, 0.9%",
            "Sodium Valproate Capsule (Slow Release), 500mg",
            "Sodium Valproate Capsule, 200 mg",
            "Sodium Valproate Syrup, 200 mg/5 Ml",
            "Sodium Valproate Tablet, 200 mg",
            "Soothing Agent + Local Anaesthetic + Steroid Ointment",
            "Soothing Agent + Local Anaesthetic + Steroid Suppository",
            "Soothing Agent + Local Anaesthetic Ointment",
            "Soothing Agent + Local Anaesthetic Suppository",
            "Spironolactone Tablet, 25 mg",
            "Spironolactone Tablet, 50 mg",
            "Streptokinase Injection, 100,000 unit-vial",
            "Streptokinase Injection, 250,000 unit-vial",
            "Streptokinase Injection, 750,000 unit-vial",
            "Sulfasalazine Tablet, 500 mg",
            "Tamoxifen Tablet, 10 mg",
            "Tamoxifen Tablet, 20 mg",
            "Tamsulosin Capsule, 400 microgram",
            "Terazosin Tablet, 2 mg",
            "Terazosin Tablet, 5 mg ",
            "Terbinafine HCl Tablet, 250 mg",
            "Tetracycline Capsule, 250 mg",
            "Tetracycline Eye Ointment, 1%",
            "Theophylline Tablet, 200 mg (slow release)",
            "Thiamine Injection, 100mg/2mL",
            "Thiamine Tablet, 100 mg",
            "Thiamine Tablet, 50 mg",
            "Tiabendazole Tablet, 500 mg",
            "Timolol Maleate Eye Drops, 0.5%",
            "Tinidazole Capsule, 500 mg",
            "Tirofiban Infusion, 250 micrograms/ml (concentrate)",
            "Tirofiban Infusion, 50 micrograms/mL",
            "Tolbutamide Tablet, 500 mg",
            "Tranexamic Acid Capsule, 250 mg",
            "Tranexamic Acid Injection, 500 mg/5mL ",
            "Tranexamic Acid Tablet, 500 mg",
            "Trihexyphenidyl Tablet, 2 mg",
            "Trihexyphenidyl Tablet, 5 mg",
            "Verapamil Tablet, 40 mg",
            "Verapamil Tablet, 80 mg",
            "Warfarin Tablet, 1 mg",
            "Warfarin Tablet, 3 mg ",
            "Warfarin Tablet, 5 mg (scored)",
            "Water for Injection",
            "Zinc Tablet, 10 mg",
            "Zinc Tablet, 20 mg",
            "5-Fluorouracil Injection, 50 mg/mL"
        ];

        foreach ($records as $key => $record) {
            ProductGenericName::query()->firstOrCreate([
                'name' => trim($record),
                'status' => 'ACTIVE',
                'created_at' => '2020-07-30 16:19:00',
                'deleted_at' => '2020-07-30 16:19:00'
            ]);
        }
        Schema::enableForeignKeyConstraints();
    }
}
