before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client)'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - 15-ci-cd-should-update-the-server
  script:
    - ssh willie@78.141.192.241 "cd /var/www/html/ssisgh/test-api && git pull origin dev
